package ru.maltsev.bybitpayerbackend.withdrawal.model;

public enum WithdrawalEventType {
    WITHDRAWAL_CREATED,
    WITHDRAWAL_QUEUED,
    WITHDRAWAL_PUBLISHED,
    ADVERTISEMENT_UPDATED,
    WITHDRAWAL_REMOVED_FROM_AD,
    ORDER_FOUND,
    REQUISITES_SENT,
    ORDER_PAID,
    MAIL_CHECK_STARTED,
    EMAIL_FOUND,
    PDF_FOUND,
    PDF_PARSED,
    VERIFICATION_SUCCEEDED,
    VERIFICATION_FAILED,
    RELEASE_SUCCEEDED,
    RELEASE_FAILED,
    ATTENTION_REQUIRED,
    COMPLETION_SEEN,
    BYBIT_API_ERROR,
    IMAPS_ERROR,
    PDF_PARSER_ERROR,
    WITHDRAWAL_CANCELLED,
    SYSTEM_RESYNC
}
